"""Create Task Table

Revision ID: 502c726aeede
Revises: 9c80390f8ce9
Create Date: 2024-02-27 20:51:25.516044

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "502c726aeede"
down_revision: str | None = "9c80390f8ce9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("task_dones",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("done_at", sa.DateTime(), nullable=True),
    sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
    sa.Column("updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),

    sa.PrimaryKeyConstraint("id"),
    )
    op.create_table("tasks",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
    sa.Column("updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
    sa.Column("creator_id", sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(["creator_id"], ["users.id"] ),
    sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    op.drop_table("task_dones")
    # ### end Alembic commands ###
